### ISSUE TITLE
作者你好，可以请问下sky_mask的获取用的是Trans4PASS对哪个数据集的训练权重吗：）

### ISSUE THREAD

**Issue by steven30currry** [qianmingduowan/Sat2Density#6]

**Comment by qianmingduowan** [comment]
<img width="638" alt="image" src="https://github.com/qianmingduowan/Sat2Density/assets/41671762/bad8c3f8-c6ac-4189-9629-b7c5f79d5738">
You can try this one

**Comment by steven30currry** [comment]
thanks a lot !


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianmingduowan/Sat2Density"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qianmingduowan/Sat2Density] 作者你好，可以请问下sky_mask的获取用的是Trans4PASS对哪个数据集的训练权重吗：） (Issue #6)





  You can try this one
