### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by zhangdan8962** [qianmingduowan/Sat2Density#7]
Hi,

I am wondering why there are 32,810 images in `CVACT/satview_correct` while 44,415 in `CVACT/streetview`? 
Similarly, there are 44,416 files in `CVUSA/19` and 44,516 in `CVUSA/panos`. It seems the number of images are not matched for both datasets.

Could you please let me know how you split the training and testing set?

**Comment by qianmingduowan** [comment]
Hi,

The data split follows the repo: https://github.com/YujiaoShi/Sat2StrPanoramaSynthesis 

I hope it can help you well.

Best

**Comment by zhangdan8962** [comment]
> Hi,
> 
> The data split follows the repo: https://github.com/YujiaoShi/Sat2StrPanoramaSynthesis
> 
> I hope it can help you well.
> 
> Best

Thank you for the reply! But I still can not get how they split the data in the repo you provided.

**Comment by qianmingduowan** [comment]
I provided it [here](https://drive.google.com/drive/folders/1pfzwONg4P-Mzvxvzb2HoCpuZFynElPCk?usp=sharing).
